config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get  'about_us', to: 'pages#about_us'
  get  'index', to: 'pages#index'
  get  'test', to: 'pages#test'
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("############Agrega un parrafo en la vista index.html.erb con el texto: Rails es genial!!!################")
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("##########################################################################################")
    Rails.logger.info("##########################################################################################")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondApp60</title>
    <meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="no-sidebar is-preload">
		<div id="page-wrapper">
    			<!-- Header -->
				<div id="header">

					<!-- Inner -->
						<div class="inner">
							<header>
								<h1><a href="index.html" id="logo">Second App Challenge</a></h1>
							</header>
						</div>

            <!-- Nav -->
						<nav id="nav">
            	<ul>
							<li><%= link_to('Home', root_path) %><li>
							<li><%= link_to('Test', test_path) %><li>
              <li><%= link_to('Dropdown', index_path) %><li>
							<li><%= link_to('About us', about_us_path) %><li>
							</ul>
						</nav>           

				</div>

        <!-- Main -->
				<div class="wrapper style1">

					<div class="container">
						<article id="main" class="special">
							<header>
                <%= yield %>
							</header>
            </article>   
          </div>         
        </div>

      <footer class="container-fluid" id="footer">
        <h4>All rights Reserved</h4>
      </footer>  

    </div>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Conozcanos !!!!!</h1>
<p>Somos los profesionales número 1 del país, diseñadores de paginas web</p>

app/views/pages/index.html.erb
<h1>Bienvenidos!!!!!</h1>
<p>Le gustaria conocernos</p>

app/views/pages/test.html.erb
<h1>Realiza el siguiente test</h1>
<%= image_tag 'helios.jpg' %>
<p>Informate</p>